#Select BT Customer
DD_SALES_CHANNEL="xpath=.//a[@class='btn btn3d menu']"
DD_CUSTOMER="arid_WIN_0_536870989"

#Verify Customer Existance
BTN_CREATE_CUSTOMER="WIN_0_536870910"
IFRAME="xpath=.//iframe[contains(@id,'P')]"
BTN_X="ardivcl"

#Go to Quote tab
TAB_QUOTE_DETAILS="xpath=.//*[@id='WIN_0_536870913']/div[2]/div[2]/div/dl/dd[3]/span[2]/a"

#Search and Select Quotation
TAB_SEARCH_QUOTE="xpath=.//*[@id='WIN_0_536880963']/div[2]/div[2]/div/dl/dd[2]/span[2]/a"

#Product Configuration
IMG_LOADING								= "xpath=.//*[@id='creating-product-spinner']"
DD_DIRECT_CONNECT_SERVICE_PROVIDER		= "xpath=.//select[@title='Mandatory']"
LINK_BASE_CONFIGURATION					= "xpath=.//li[*]/div/div/span[@title='Base Configuration']"
BOX_INTERCONNECT_LOCATION				= "xpath=.//div[@rel='INTERCONNECT LOCATION']/div[2]"
DD_INTERCONNECT_LOCATION				= "xpath=.//div[@rel='INTERCONNECT LOCATION']/div[3]/select"
LINK_CCD								= "xpath=.//span[contains(text(),'Cloud Connect Direct')]"
LINK_CFS								= "xpath=.//span[contains(text(),'Cloud Firewall Services')]"
LINK_CAS								= "xpath=.//i/../span[contains(text(),'Cloud Acceleration Service')]"
#LINK_PROVIDER_CONNECTION				= "xpath=.//li[*]/div/div/span[@title='Provider Connection']"
LINK_MS_EXP_BASE_CONF					= "xpath=.//ul[not(contains(@style,'none'))]/../span[@title='Base Configuration']"
LINK_MS_EXP_NAT							= "xpath=.//li[*]/div/i[contains(@class,'NOT_PRICED')]/../div/div/div/span[@title='NAT']"
LINK_MS_EXP_ROUTE_SVCONN				= "xpath=.//li[*]/div/div/span[@title='MS Express Route Service Connection']"
LINK_MS_EXP_CUS_ADD_SPACE				= "xpath=(.//li[*]/div/div/div/div/span[@title='Customer Address Space'])[last()]"
TXT_SUMMARY								= "xpath=.//div[@rel='summary']/div[2]"
STATUS_LOADING							= "xpath=.//*[@id='statusBarModal']"
BOX_BANDWIDTH							= "xpath=.//div[@rel='BANDWIDTH']/div[2]"
DD_BANDWIDTH							= "xpath=.//div[@rel='BANDWIDTH']/div[3]/select"
BOX_CONN_TYPE							= "xpath=.//div[@rel='CONNECTION TYPE']/div[2]"
DD_CONN_TYPE							= "xpath=.//div[@rel='CONNECTION TYPE']/div[3]/select"
BOX_AF									= "xpath=.//div[@rel='EF BANDWIDTH']/div[2]"
BOX_DE									= "xpath=.//div[@rel='AF BANDWIDTH']/div[2]"
DD_AF									= "xpath=.//div[@rel='EF BANDWIDTH']/div[3]/select"
DD_DE									= "xpath=.//div[@rel='AF BANDWIDTH']/div[3]/select"
LINK_NAT								= "xpath=.//li[*]/div/div/span[@title='NAT']"
LINK_CUSTOMER_ADD_SPACE					= "xpath=.//li[*]/div/div/span[@title='Customer Address Space']"
LINK_VPN_SPEC							= "xpath=.//li[*]/div/div/span[@title='VPN Specification']"
LINK_CLOUD_FW_SERVICE					= "xpath=.//li[*]/div/div/span[@title='Cloud Firewall Service']"
LINK_CLOUD_ACC_SERVICE					= "xpath=.//li[*]/div/div/span[@title='Cloud Acceleration Service']"
LINK_CLOUD_SERVICE_LEG					= "xpath=.//li[*]/div/div/span[@title='Cloud Service Leg']"
LINK_CSL_FW_SERVICE						= "xpath=.//li[*]/div/div/div/div/span[@title='Firewall Service']"
LINK_CSL_ACC_SERVICE					= "xpath=.//li[*]/div/div/div/div/span[@title='Acceleration Service']"
LINK_FW_SERVICE							= "xpath=.//li[*]/div/div/span[@title='Firewall Service']"
BOX_POLICY_CHANGE_MANAGEMENT_TYPE		= "xpath=.//div[@rel='POLICY CHANGE MANAGEMENT TYPE']/div[2]"
DD_POLICY_CHANGE_MANAGEMENT_TYPE		= "xpath=.//div[@rel='POLICY CHANGE MANAGEMENT TYPE']/div[3]/select"
BOX_MY_ACCOUNT_PORTAL_DCF_LINK			= "xpath=.//div[@rel='MY ACCOUNT PORTAL DCF LINK']/div[2]"
INPUT_MY_ACCOUNT_PORTAL_DCF_LINK		= "xpath=.//div[@rel='MY ACCOUNT PORTAL DCF LINK']/div[3]/input"
LINK_ACC_SERVICE						= "xpath=.//li[*]/div/div/span[@title='Acceleration Service']"
CONFIGURE								= "xpath=.//div[2]/a[contains(text(),'Configure')]"
CONFIGURE_ALL							= "xpath=(.//a[text()='Configure All'])"
LINK_TO_NEW								= "xpath=.//div[not(@class='pane')]/select[@id='creatable_rel_ctnr']"
LINK_TO_EXISTING						= "choosable_rel_ctnr"
BTN_ADD									= "xpath=.//button[@ng-click='addRelations()'][contains(text(),'Add')]"
BTN_OK									= "xpath=.//div[@class='relationship-dialog ui-dialog-content ui-widget-content ui-resizable']/div[1]/div[2]/div/button[contains(text(),'Ok')]"
LINK_QUOTE_OPT_DETAILS					= "xpath=.//*[@id='quoteOption']"
BTN_OK_RFO								= "xpath=.//div[@role='dialog'][not(contains(@style,'display: none'))]//button"
UPLOAD_SUCCESSFUL						= "xpath=.//*[text()='Upload Successful']"
STATUS_SUBMITTED						= "xpath=.//*[text()='Submitted']"