LINK_UPLOAD_CSV                                 ="xpath=.//*/div[contains(text(),'Upload CSV(Bulk Manage Number Blocks)')]"

BTN_SIGN_ON                                     ="xpath=.//*/input[@value='Sign On']"
BTN_UPLOAD_CSV_BROWSE                           ="xpath=.//*/form/fieldset/div/label[contains(text(),'File:')]/../input"
BTN_UPLOAD_CSV_SUBMIT                           ="xpath=.//*/table/tbody/tr/td/em/button[contains(text(),'Submit')]"
BTN_SUCCESS_OK                                  ="xpath=.//*/tbody[@class='x-btn-small x-btn-icon-small-left']/tr/td/em/button[contains(text(),'OK')]"

CBO_UPLOAD_CSV_COUNTRY                          ="xpath=.//*/form/fieldset/div/div/label[contains(text(),'Country:')]/../div/div/input"
CBO_UPLOAD_SCV_PRODUCT_CODE                     ="xpath=.//*/form/fieldset/div/div/label[contains(text(),'Product Code:')]/../div/div/input"
LINK_MANAGE_NB		                            ="xpath=.//*/div[contains(text(),'Manage Number Block')]"
MNB_OPERATION									="xpath=.//label[contains(text(),'Choose the manage number')]/../div[1]/div[1]/div/div/input"
MNB_COUNTRY										="xpath=.//label[contains(text(),'Country :')]/../div[2]/div/div/input[1]"
MNB_PRODUCT_CODE								="xpath=.//label[contains(text(),'Product Code :')]/../div[3]/div/div/input[1]"
ALLOCATE_NUMBER_BLOCK							="xpath=.//div[contains(text(),'Allocate Number Block')]"
LINK_UPDATE_OPERATOR							="xpath=.//*/div[contains(text(),'Update Operator Details')]"
OPERATOR_COUNTRY								="xpath=.//input[@name='countryList']"
BTN_OPERATOR_NEXT								="xpath=.//*[text()='of 9']/..//following-sibling::td[2][//button[not(@aria-disabled)]]"
TXT_BTSP										="xpath=.//div[contains(text(),'BTSP')]"
ACTIVATE_NUMBER_BLOCK							="xpath=.//div[contains(text(),'Activate Number Block')]"
LOADING											="xpath=.//div[@class='loading-indicator'][contains(text(),'Loading...')]"
RESPONSE_STATUS									="xpath=.//span[contains(text(),'Response Status')]"
SAVE											="xpath=.//*[text()='Detail']/../../..//button[not(@aria-disabled)]"
CUSTOMER_NAME									="xpath=.//input[@name='customer']"
START_NUMBER									="xpath=.//input[@name='startNumber']"
END_NUMBER										="xpath=.//input[@name='endNumber']"
MNUM_ID											="xpath=.//input[@name='orderNumber']"
HOME											="xpath=.//span[contains(text(),'Home')]"
