BTN_LOGIN                   			    ="xpath=.//*[@id='needToDisplayOnce']/table/tbody/tr/td/table/tbody/tr[4]/td[1]/input"
BTN_FILER                   			    ="xpath=.//*[@title='Filter']"
BTN_ORDERDETAIL2           				    ="xpath=//tr//td//input[@id='button0']"
BTN_NEXT_PAGE               			    ="xpath=.//*[@title='Next Page']"
BTN_SAVE                                    ="xpath=.//*[@id='SaveTE']"
BTN_UPDATE_RPACS                            ="xpath=.//*[@id='table6']/tbody/tr/td/input[@value='Update rPACS']"
RBTN_1STORDER              				    ="xpath=.//*[@id='orderTable_table']/tbody/tr/td[1]/input"

IFRAME_MENU                 			    ="xpath=.//iframe[@id='menu']"
IFRAME_CONTENT              			    ="xpath=.//iframe[@id='content']"
IFRAME_ARIADNETHREAD        			    ="xpath=.//iframe[@id='ariadneThread']"
IFRAME_MATRIX_ATTR                          ="xpath="

TXT_FILTER_CUSTOMERID_ORDERLIST     	    ="xpath=.//*[@id='FilterMyOrders05']/input"
TXT_FILTER_CUSTOMERNAME_ORDERLIST   	    ="xpath=.//*[@id='FilterMyOrders06']/input"
TXT_FILTER_STATUS_TASKINSERVICE     	    ="xpath=.//*[@name='ec_f_status']"
TXT_FEEDBACK_USECLASSIC             	    ="xpath=.//tr[@class='feedbackWarning']/td[@align='left'][contains(text(),'use Classic')]"
TXT_TRUNK_WHITE_LIST                        ="xpath=.//*/tbody/tr[@class='filaimpar']/td[contains(text(),'Trunk White List:')]/../td/input[@class='crudmand']"
TXT_SWITCH_NNNN_CODE                        ="xpath=.//*/tbody/tr[@class='roweven']/td[contains(text(),'Switch / NNNN Code:')]/../td/input[@class='crudmand']"
TXT_IPMS_SRN                                ="xpath=.//*/tbody/tr[@class='roweven']/td[contains(text(),'IPMS Service Reference Number (SRN):')]/../td/input[@class='crudmand']"
TXT_IPMS_ENTERPRISE_ID                      ="xpath=.//*/tbody/tr/td[contains(text(),'IPMS Enterprise Id:')]/../td/input[@class='crudmand']"
TXT_IPMS_CORP_ID                            ="xpath=.//*/tbody/tr/td[contains(text(),'IPMS Corporate Id:')]/../td/input[@class='crudmand']"
TXT_IPMS_ORD_NUM                            ="xpath=.//*/tbody/tr/td[contains(text(),'IPMS Order Number:')]/../td/input[@class='crudmand']"
TXT_SVC_LOC_ID                              ="xpath=.//*/input[@class='crudmand']"
TXT_MOD_TRUNK_WHITE_LIST                    ="xpath=.//*/tbody/tr[@class='roweven']/td[contains(text(),'Trunk White List:')]/../td/input[@class='crudmand']"

TXT_MOD_SWITCH_NNNN_CODE                    ="xpath=.//*/tbody/tr[@class='roweven']/td[contains(text(),'Switch / NNNN Code:')]/../td/input[@class='crudmand']"
TXT_MOD_ICG_TRUNK_OSS                       ="xpath=.//*/tbody/tr[@class='roweven']/td[contains(text(),'ICg Trunk OSS ID:')]/../td/input[@class='crudmand']"
TXT_MOD_ICG_IPMS_SRN                        ="xpath=.//*/tbody/tr[@class='roweven']/td[contains(text(),'ICg IPMS SRN:')]/../td/input[@class='crudmand']"
TXT_MOD_ICG_CORP_ID                         ="xpath=.//*/tbody/tr[@class='filaimpar']/td[contains(text(),'ICg IPMS CORP ID:')]/../td/input[@class='crudmand']"
TXT_TRUNK_GROUP_OSS_ID                      ="xpath=.//*/tbody/tr[@class='roweven']/td[contains(text(),'Trunk Group OSS Id:')]/../td/input[@class='crudmand']"
TXT_TRUNK_OSS_ID                            ="xpath=.//*/tbody/tr[@class='roweven']/td[contains(text(),'Trunk OSS Id:')]/../td/input[@class='crudmand']"
TXT_ICG_TRUNK_OSS_ID                        ="xpath=.//*/tbody/tr[@class='roweven']/td[contains(text(),'ICg Trunk OSS ID:')]/../td/input[@class='crudmand']"
TXT_ICG_IPMS_SRN                            ="xpath=.//*/tbody/tr[@class='roweven']/td[contains(text(),'ICg IPMS SRN:')]/../td/input[@class='crudmand']"
TXT_ICG_IPMS_CORP_ID                        ="xpath=.//*/tbody/tr[@class='filaimpar']/td[contains(text(),'ICg IPMS CORP ID:')]/../td/input[@class='crudmand']"
TXT_PNMC_PORT_IN_DATE_NN                    ="xpath=.//*[@id='1']/td[8]/input"
TXT_PNMC_PORT_IN_DATE_P                     ="xpath=.//*[@id='2']/td[8]/input"
TXT_PNMC_PORT_OUT_DATE_NN                   ="xpath=.//*[@id='1']/td[9]/input"
TXT_PNMC_PORT_OUT_DATE_P                    ="xpath=.//*[@id='2']/td[9]/input"
TXT_PNMC_CUT_OVER_DATE_NN                   ="xpath=.//*[@id='1']/td[12]/input"
TXT_PNMC_CUT_OVER_DATE_P                    ="xpath=.//*[@id='2']/td[12]/input"
TXT_PNMC_GSP_P                              ="xpath=.//*[@id='2']/td[27]/input"    
TXT_PNMC_LSP_P                              ="xpath=.//*[@id='2']/td[28]/input"

CBO_CUST_ACT_SUPPORT                	    ="xpath=.//*/tbody/tr/td[contains(text(),'Customer Activation')]/../td/select[@class='crudmand']"
CBO_CUST_ACT_SUPPORT_NO             	    ="xpath=.//*/tbody/tr/td[contains(text(),'Customer Activation')]/../td/select[@class='crudmand']/option[text()='NO']"
CBO_SERV_TEST_REQ                   	    ="xpath=.//*/tbody/tr/td[contains(text(),'Service test required:')]/../td/select[@class='crudmand']"
CBO_SERV_TEST_REQ_YES               	    ="xpath=.//*/tbody/tr/td[contains(text(),'Service test required:')]/../td/select[@class='crudmand']/option[text()='YES']"
CBO_SERV_TEST_REQ_NO                	    ="xpath=.//*/tbody/tr/td[contains(text(),'Service test required:')]/../td/select[@class='crudmand']/option[text()='NO']"
CBO_FULL_SERV_CPE_TEST              	    ="xpath=.//*/tbody/tr/td[contains(text(),'Full service/CPE test Required:')]/../td/select[@class='crudmand']"
CBO_FULL_SERV_CPE_TEST_NO           	    ="xpath=.//*/tbody/tr/td[contains(text(),'Full service/CPE test Required:')]/../td/select[@class='crudmand']/option[text()='NO']"
CBO_CSC_ACCEPTED                    	    ="xpath=.//*/tbody/tr/td[contains(text(),'CSC Accepted:')]/../td/select[@class='crudnone']"
CBO_CSC_ACCEPTED_YES                	    ="xpath=.//*/tbody/tr/td[contains(text(),'CSC Accepted:')]/../td/select[@class='crudnone']/option[text()='YES']"
CBO_CUST_CONFIG_DATA_AVAI                   ="xpath=.//*/tbody/tr/td[contains(text(),'Customer Config Data Available:')]/../td/select[@class='crudnone']"
CBO_CUST_KEEP_CPE                           ="xpath=.//*/td[contains(text(),'Customer Keeping CPE:')]/../td/select[@class='crudmand']"
CBO_CEASE_ACCESS_TAIL                       ="xpath=.//*/td[contains(text(),'Cease Access Tail:')]/../td/select[@class='crudmand']"
CBO_RECOVER_OWN_ACCESS                      ="xpath=.//*/td[contains(text(),'Recover Own Access:')]/../td/select[@class='crudmand']"
CBO_RECOVER_PORT                            ="xpath=.//*/td[contains(text(),'Recover Port:')]/../td/select[@class='crudmand']"
CBO_SERV_TEST_REQ_MOD                       ="xpath=.//*/td[contains(text(),'Service test required:')]/../td/select[@class='crudmand']"
CBO_ALLOCATE_NEW_NETWORK_RESOURCES          ="xpath=.//*/tbody/tr[@class='roweven']/td[contains(text(),'Allocate New Network Resources')]/../td/select[@class='crudmand']"
CBO_BILLING_ONLY                            ="xpath=.//*/tbody/tr[@class='filaimpar']/td[contains(text(),'Billing Only:')]/../td/select[@class='crudmand']"
CBO_CEASE_EXISTING_CPE                      ="xpath=.//*/tbody/tr[@class='roweven']/td[contains(text(),'Cease Existing CPE:')]/../td/select[@class='crudmand']"
CBO_CHANGE_CPE                              ="xpath=.//*/tbody/tr[@class='filaimpar']/td[contains(text(),'Change CPE')]/../td/select[@class='crudmand']"
CBO_CHANGE_ETH_CFN                          ="xpath=.//*/tbody/tr[@class='roweven']/td[contains(text(),'Change Ethernet CFN:')]/../td/select[@class='crudmand']"
CBO_CHANGE_OLO_DSL                          ="xpath=.//*/tbody/tr[@class='filaimpar']/td[contains(text(),'Change OLO/DSL:')]/../td/select[@class='crudmand']"
CBO_CHANGE_TRANSMISSION_PATH                ="xpath=.//*/tbody/tr[@class='roweven']/td[contains(text(),'Change Transmission Path:')]/../td/select[@class='crudmand']"
CBO_NW_RECONFIG_REQUIRED                    ="xpath=.//*/tbody/tr[@class='filaimpar']/td[contains(text(),'Network Reconfiguration Required:')]/../td/select[@class='crudmand']"
CBO_OWN_ACCESS_MOD                          ="xpath=.//*/tbody/tr[@class='roweven']/td[contains(text(),'Own access Modification:')]/../td/select[@class='crudmand']"
CBO_SRV_OUTAGE_REQUIRED                     ="xpath=.//*/tbody/tr[@class='filaimpar']/td[contains(text(),'Service Outage required:')]/../td/select[@class='crudmand']"
CBO_ACCESS_ALARM_TEST_REQ                   ="xpath=.//*/tbody/tr[@class='roweven']/td[contains(text(),'Access Alarm Test Required:')]/../td/select[@class='crudmand']"
CBO_ACCESS_ALARM_TEST_EXECUTED              ="xpath=.//*/tbody/tr[@class='roweven']/td[contains(text(),'Access Alarm Test Executed:')]/../td/select[@class='crudmand']"
CBO_ACCESS_ALARM_TEST_RESULT                ="xpath=.//*/tbody/tr[@class='filaimpar']/td[contains(text(),'Access Alarm Test Result:')]/../td/select[@class='crudmand']"
CBO_ONSITE_CPE_TEST_EXECUTED                ="xpath=.//*/tbody/tr[@class='roweven']/td[contains(text(),'On site CPE Test Executed:')]/../td/select[@class='crudmand']"
CBO_ONSITE_CPE_TEST_RESULT                  ="xpath=.//*/tbody/tr[@class='filaimpar']/td[contains(text(),'On site CPE Test Result:')]/../td/select[@class='crudmand']"
CBO_ENCRYPTION_APPLIED                      ="xpath=.//*/tbody/tr[@class='roweven']/td[contains(text(),'Encryption Applied?:')]/../td/select[@class='crudmand']"
CBO_SRV_TEST_EXECUTED                       ="xpath=.//*/tbody/tr[@class='roweven']/td[contains(text(),'Service test Executed:')]/../td/select[@class='crudmand']"
CBO_SRV_TEST_RESULT                         ="xpath=.//*/tbody/tr[@class='filaimpar']/td[contains(text(),'Service test Result:')]/../td/select[@class='crudmand']"
CBO_ONSITE_CPE_TEST_REQ                     ="xpath=.//*/tbody/tr[@class='roweven']/td[contains(text(),'On site CPE Test Required:')]/../td/select[@class='crudmand']"
CBO_FULL_SRV_CPE_TEST_EXECUTED              ="xpath=.//*/tbody/tr[@class='roweven']/td[contains(text(),'Full service/CPE test Executed:')]/../td/select[@class='crudmand']"
CBO_FULL_SRV_CPE_TEST_RESULT                ="xpath=.//*/tbody/tr[@class='filaimpar']/td[contains(text(),'Full service/CPE test Result:')]/../td/select[@class='crudmand']"
CBO_PORT_IN_OUT_COMPLETED                   ="xpath=.//*/table[@id='grpPort In/Out and Test Service']/tbody/tr/td[contains(text(),'Port In/Out Completed?:')]/../td/select"
CBO_ACCESS_ORDER_ACCEPTED		            ="xpath=.//*/table[@id='grpAccess Order Accepted']/tbody/tr/td[contains(text(),'Access Order Accepted:')]/../td/select"
CBO_BILLING_RECORD_SETUP		            ="xpath=.//td[text()='Billing Record Setup: ']/..//*[@id='att0']"

OPT_ID_MYORDERS                     	    ="xpath=.//*[@id='MyOrders_table']/tbody/tr[1]/td[1]/input"

LINK_SERVICENUMBER                  	    ="xpath=.//a[@class='hrefLinkExt']"
LINK_ALLTASKS                       	    ="xpath=.//td[@class='filaimpar']/a[@class='hrefLink'][contains(text(),'All Tasks')]"
LINK_CRE_UPDATE_COMPLETE                    	    ="xpath=.//td[@class='feedbackWarning']/b[contains(text(),'Please confirm whether CRE Update completed?')]"
LINK_FEEDBACKYES                    	    ="xpath=.//td[@class='feedbackWarning']/a[contains(text(),'YES')]"
LINK_BREADCRUMBSTASKINSERVICE       	    ="xpath=.//td[@id='menuText']/a[@class='threadlink'][contains(text(),'Tasks In Service')]"
LINK_SERV_OVERVIEW                  	    ="xpath=.//*[@id='menuText']/a[4]"
LINK_TASK_IN_SERV                   	    ="xpath=.//*[@id='menuText']/a[5]"  
LINK_TASKDETAILS                            ="xpath=.//*[@id='menuText']/a[6]"
LINK_ALL_TASKS                      	    ="xpath=.//a[text()='All Tasks']"
LINK_MATRIXCONFIG                           ="xpath=.//*[@title='MatrixConfig']"
LINK_NUM_BLK_MATRIX_CONFIG                  ="xpath="
LINK_NUMBER_BLK_EXPORT                      ="xpath=.//a[text()='Number Block Export']"

LBL_TOTAL_RESULTS_FOUND             	           ="xpath=.//*[@id='ec_table']/thead/tr[1]/td/table/tbody/tr/td[1]"


DATE_PICKER_FULL_SERV_CPE_TEST                      ="xpath=.//*/td[contains(text(),'Scheduled Full service/CPE test Date:')]/../td/table/tbody/tr/td/a/img[@alt='Date']"
DATE_PICKER_NOTIFY_CUST_SVC_READY_DATE              ="xpath=.//*/td[contains(text(),'Notify Cust Svc Ready Date:')]/../td/table/tbody/tr/td/a/img[@alt='Date']"
DATE_PICKER_ACCESS_ALARM_TEST_REQ                   ="xpath=.//*/td[contains(text(),'Scheduled Access Alarm Test Date:')]/../td/table/tbody/tr/td/a/img[@alt='Date']"
DATE_PICKER_SCHEDULED_ONSITE_CPE_TEST_DATE          ="xpath=.//*/td[contains(text(),'Scheduled On site CPE Test Date:')]/../td/table/tbody/tr/td/a/img[@alt='Date']"
DATE_PICKER_SCHEDULED_SERV_TEST_DATE                ="xpath=.//*/td[contains(text(),'Scheduled Service test Date:')]/../td/table/tbody/tr/td/a/img[@alt='Date']"
DATE_PICKER_ONSITE_CPE_TEST_DATE                    ="xpath=.//*/td[contains(text(),'Execution On site CPE Test Date:')]/../td/table/tbody/tr/td/a/img[@alt='Date']"
DATE_PICKER_EXECUTION_ACCESS_ALARM_TEST_DATE        ="xpath=.//*/td[contains(text(),'Execution Access Alarm Test Date:')]/../td/table/tbody/tr/td/a/img[@alt='Date']"
DATE_PICKER_EXECUTION_SERVICE_TEST_DATE             ="xpath=.//*/td[contains(text(),'Execution Service test Date:')]/../td/table/tbody/tr/td/a/img[@alt='Date']"
DATE_PICKER_EXECUTION_FILL_SERVICE_CPE_TEST_DATE    ="xpath=.//*/td[contains(text(),'Execution Full service/CPE test Date:')]/../td/table/tbody/tr/td/a/img[@alt='Date']"
DATE_PICKER_PNMC_NN_1                               ="xpath=.//*[@id='1']/td[8]/img"
DATE_PICKER_PNMC_NN_2                               ="xpath=.//*[@id='1']/td[9]/img"
DATE_PICKER_PNMC_NN_3                               ="xpath=.//*[@id='1']/td[12]/img"
DATE_PICKER_PNMC_P_1                                ="xpath=.//*[@id='2']/td[8]/img"
DATE_PICKER_PNMC_P_2                                ="xpath=.//*[@id='2']/td[8]/img"
DATE_PICKER_PNMC_P_3                                ="xpath=.//*[@id='2']/td[12]/img"

CALENDER_IMG		="xpath=.//img[contains(@src,'calender.gif')]"
TODAYSDATE			="xpath=.//font[@color='red']/b/a"

LBL_TASK_ENDED                                      ="xpath=.//*[@id='w1']/table/tbody/tr/td/table/tbody/tr/td"
#added by Azry 23052018 - moving variables from TAHITI_Resource.txt
BTN_YANKTASK									="button1"
BTN_TASKDETAIL									="button2"	
BTN_ENDTASK										="BotonEnd"
BTN_ORDERSEARCH   								="button1"
BTN_SEARCH  									="button1"
BTN_YES_LEGAL									="YES"
BTN_ORDERDETAIL									="button0" 
TXT_SEARCH   									="txtSearch" 
TXT_USERNAME									="user" 
TXT_PWD											="password"
LINK_MYORDERS									="opm1"
ORDERSTATUS_TASKINSERVICE						="Execution"
OPT_TASKID										="IdNumber"
LIST_ORDERTABLE    								="orderTable_table"
FORM_ORDERDETAIL    							="orderDetail"
FORM_SERVICELIST    							="ec"
FORM_TASKDETAILS    							="formTaskDetails"
TASK_FOR_SERVICE_LIST							="//table[@id='ec_table']/tbody/tr"
TABLE_HEADER_TASK_ID    						="Headerec01"
#end added by Azry 23052018 - moving variables from TAHITI_Resource
TXT_ICG_TRUNK_OSS_ID_T1							="xpath=//*/tbody/tr[@class='filaimpar']/td[contains(text(),'ICg Trunk OSS ID:')]/../td/input[@class='crudmand']"
TXT_VLAN_ID										="xpath=.//*/tbody/tr[@class='roweven']/td[contains(text(),'VLAN ID:')]/../td/input[@class='crudmand']"