##VLP Page
#LOADING_VLP_PAGE			="xpath=.//*[@id='loading']"
LOADING_VLP_PAGE			="xpath=.//*[@id='loading']/div/span[contains(text(),'Voice Logical Provisioning')]"
SITE_TABLE					="xpath=.//*[@id='x-auto-65']"
SEARCH_SITE_INPUT			="xpath=.//*[@id='x-auto-70-input']"
LOADING_MSG_VLP				="xpath=.//*[contains(text(),'Loading')]"
#LOADING_MSG_VLP				="xpath=.//*[@class='ext-el-mask-msg']/div[contains(text(),'Loading')]"
#SELECTED_SITE_ROW			="xpath=.//*[@id='x-auto-84_x-auto-1898']"
OPERATION_INPROGRESS_MSG	="xpath=.//*[contains(text(),'Please wait')]"
#SEARCHED_SITE_ID			="xpath=.//*[@class='x-grid3-cell-inner x-grid3-col-siteId'][contains(text(),'${BranchSiteId}')]"
#SEARCHED_SITE_ID			="xpath=.//*[@class='x-grid3-row x-grid3-row-over'][contains(text(),'${BranchSiteId}')]"
#SEARCHED_SITE_ID			="xpath=.//*[@class='x-grid3-cell-inner x-grid3-col-siteId'][contains(text(),'${BranchSiteId}')]"
#[contains(text(),'1278360')]
SEARCHED_SITE_ID			="xpath=.//*[@class='x-grid3-cell-inner x-grid3-col-siteId']"
#DELETE_BTN					="xpath=.//*[@aria-describedby='x-auto-203']"
#DELETE_BTN					="xpath=.//*[@style='background-image: url('http://vlp-ov-dev01.intra.bt.com:81/vlp-occ/oasis/97CDDB931FA3288320A6BA0C5394A3B3.cache.png')']"
FIRST_LINE_SERVICE			="xpath=.//*[@class='x-grid3-col x-grid3-cell x-grid3-td-publicNumber x-grid-cell-first ']"
DELETE_BTN					="xpath=(.//*[text()='Elements']/../../..//table[not(contains(@class,'x-hide-display'))]/*/*/*/em/button)[2]"
DELETE_MSG					="xpath=.//*[@class='ext-mb-text'][contains(text(),'The selected objects will be deleted from the network. Do you wish to proceed?')]"
EMPTY_LINE_SERVICES			="xpath=.//*[@class='x-grid-empty']"
YES_DELETE_BTN				="xpath=.//*/em/button[contains(text(),'Yes')]"
CEASE_MSG					="xpath=.//*[@class='x-form-item-label'][contains(text(),'Cease Date')]"
PROCEED_BTN					="xpath=.//*[@class='gwt-Button x-component x-column'][contains(text(),'Proceed')]"
#FIRST_NUMBER				="xpath=.//*/table/tbody/tr/td[@class='x-grid3-col x-grid3-cell x-grid3-td-publicNumber x-grid-cell-first']"
FIRST_NUMBER_CELL			="xpath=.//*[@class='x-grid3-col x-grid3-cell x-grid3-td-publicNumber x-grid-cell-first']"


#SEARCHED_SITE_ID			="xpath=.//*[@class='x-grid3-row']/table/tbody/tr/td/div[contains(text(),'${BranchSiteId}')]"
#SEARCHED_SITE_ID			="xpath=.//*[@class='x-grid3-row']/table/tbody/tr[contains(normalize-space(.),'${BranchSiteId}')]"


#.//*[@id='x-auto-140-content']

BFG_MAINPAGE				="xpath=.//*[@id='ApplicationName']"
USER_PROFILE_GROUP			="xpath=.//*[@id='ApplicationName']/div/form/center/table/tbody/tr/td/p/select"
SUBMIT_BFG_BTN				="xpath=.//*[@id='ApplicationName']/div/form/center/table/tbody/tr/td/input"



APP_TAB						="xpath=.//*[@id='tabApplications']"
APP_PORTAL					="xpath=.//*[@id='portalsCategoriesList']"
SERVICE_REQUEST_LINK		="xpath=.//*[contains(text(),'Service Request Management_SOJ')]"
CONTENT_PANEL				="xpath=.//*[@id='MainContentPanel']"
RAISE_REQUEST_TAB			="xpath=.//*[contains(text(), 'Raise a Request')]"
RAISE_REQUEST_CATALOGUE_TAB	="xpath=.//*[contains(text(), 'Raise request from Catalogue')]"
CUST_DROPDOWN				="xpath=.//*[@id='s2id_MainContent_RightMainPanel_ControlPanel_ctl00_DrpDownCustomerList']"
CUST_INPUT					="xpath=/html/body/div[7]/div/input"
CONTRACT_LOADING			="xpath=.//*[@id='CatalogueContainer']/div[1]/div[5]/div"
CONTRACT_DROPDOWN			="xpath=.//*[@id='s2id_MainContent_RightMainPanel_ControlPanel_ctl00_DrpDownContractList']"
CONTRACT_INPUT				="xpath=/html/body/div[8]/div/input"
CATALOGUE_PAGE				="xpath=.//*[@id='cataloguepage']"
SERVICE_SEARCH				="xpath=.//*[@id='AllServiceSeach']"
SERVICE_SEARCH_INPUT		="xpath=.//*[@id='MainContent_RightMainPanel_ControlPanel_ctl00_TxtBoxSearchService']"
SERVICE_SELECTED			="xpath=.//*[@id='MainContent_RightMainPanel_ControlPanel_ctl00_ServiceView']"
SERVICE_PANEL				="xpath=.//*[@id='MainContent_UpdatePanel1']"
ADD_BASE_USER				="xpath=.//*[contains(text(),'Add Base User-I [OCC]')]"
ADD_BASE_USER_BTN			="xpath=.//*[@id='ctl00_MainContent_RepeaterServiceCtrl_ctl02_btnAddtoCart']"
CONTINUE_BTN				="xpath=.//*[@id='MainContent_btnContinue']"
SITE_SERVICE_CONFIG			="xpath=.//*[@id='MainContent_NestedGrid_SiteServiceConfig']/div"
SELECT_SITE_BTN				="xpath=.//*[@id='MainContent_NestedGrid_lnkbtnAddSite']"
SITE_LIST					="xpath=.//*[@id='MainContent_UpdatePanel1']/div[1]"
COUNTRY_DROPDOWN			="xpath=.//*[@id='s2id_MainContent_RightMainPanel_ControlPanel_ctl00_ddlCountry']/a"
COUNTRY_INPUT				="xpath=.//*[@id='select2-drop']/div/input"
SITE_LOADING				="xpath=.//*[@id='PageOverlay']"
UPDATE_BTN					="xpath=.//*[@id='MainContent_NestedGrid_rptSite_childRptService_0_btnConfigure_0']"
CONFIG_PAGE					="xpath=.//*[@id='MainContent_UPServiceConfig']/div"
DEVICE_TYPE_DROPDOWN		="xpath=.//*[@id='s2id_MainContent_ATT_1_11034']/a"
FIRST_NAME_INPUT			="xpath=.//*[@id='MainContent_ATT_1_11029']"
LAST_NAME_INPUT				="xpath=.//*[@id='MainContent_ATT_1_11030']"
EMAIL_INPUT					="xpath=.//*[@id='MainContent_ATT_1_11961']"
PUBLIC_NUM_INPUT			="xpath=.//*[@id='MainContent_ATT_1_5577']"
PRIVATE_NUM_INPUT			="xpath=.//*[@id='MainContent_ATT_1_4499']"
OPTIONAL_MGS_DROPDOWN		="xpath=.//*[@id='s2id_MainContent_ATT_1_11035']/a"
USERSELF_ACCESS_DROPDOWN	="xpath=.//*[@id='s2id_MainContent_ATT_1_11032']/a"
CLASS_OF_SERVICE_INPUT		="xpath=.//*[@id='MainContent_ATT_1_2825']"
DESCRIPTIVE_TEXT_INPUT		="xpath=.//*[@id='MainContent_ATT_1_11033']"
REQUEST_FORM_PAGE			="xpath=.//*[@id='RequestFormPanel']"
CONFIRMATION_PAGE			="xpath=.//*[@id='ConfirmationPanel']/div[2]"
CUSTOMER_REFERENCE_INPUT	="xpath=.//*[@id='MainContent_txt_CustomerReference']"
SUBMIT_BTN					="xpath=.//*[@id='MainContent_btnSubmit']"
CONFIRMATION_PANEL			="xpath=//*[@id='ConfirmationPanel']/div[2]/table[2]/tbody/tr[1]/th[2]"


