##BFG_Login##
GSP_LOGIN					="xpath=.//*[@id='main']/div/div[1]/div[1]/div/div[2]/div"
LOGIN_USERNAME				="xpath=.//*[@id='username']"
LOGIN_PASSWORD				="xpath=.//*[@id='password']"
BTN_LOGIN					="xpath=.//*[@id='login_button']"
ACCEPT_BUTTON				="xpath=/html/body/div[2]/div/div/div[2]/div/form/div[4]/input"

##BFG Page
BFG_MAINPAGE				="xpath=.//*[@id='ApplicationName']"
USER_PROFILE_GROUP			="xpath=.//*[@id='ApplicationName']/div/form/center/table/tbody/tr/td/p/select"
SUBMIT_BFG_BTN				="xpath=.//*[@id='ApplicationName']/div/form/center/table/tbody/tr/td/input"



APP_TAB						="xpath=.//*[@id='tabApplications']"
APP_PORTAL					="xpath=.//*[@id='portalsCategoriesList']"
SERVICE_REQUEST_LINK		="xpath=.//*[contains(text(),'Service Request Management_SOJ')]"
CONTENT_PANEL				="xpath=.//*[@id='MainContentPanel']"
RAISE_REQUEST_TAB			="xpath=.//*[contains(text(), 'Raise a Request')]"
RAISE_REQUEST_CATALOGUE_TAB	="xpath=.//*[contains(text(), 'Raise request from Catalogue')]"
CUST_DROPDOWN				="xpath=.//*[@id='s2id_MainContent_RightMainPanel_ControlPanel_ctl00_DrpDownCustomerList']"
CUST_INPUT					="xpath=/html/body/div[7]/div/input"
CONTRACT_LOADING			="xpath=.//*[@id='CatalogueContainer']/div[1]/div[5]/div"
CONTRACT_DROPDOWN			="xpath=.//*[@id='s2id_MainContent_RightMainPanel_ControlPanel_ctl00_DrpDownContractList']"
CONTRACT_INPUT				="xpath=/html/body/div[8]/div/input"
CATALOGUE_PAGE				="xpath=.//*[@id='cataloguepage']"
SERVICE_SEARCH				="xpath=.//*[@id='AllServiceSeach']"
SERVICE_SEARCH_INPUT		="xpath=.//*[@id='MainContent_RightMainPanel_ControlPanel_ctl00_TxtBoxSearchService']"
SERVICE_SELECTED			="xpath=.//*[@id='MainContent_RightMainPanel_ControlPanel_ctl00_ServiceView']"
SERVICE_PANEL				="xpath=.//*[@id='MainContent_UpdatePanel1']"
ADD_BASE_USER				="xpath=.//*[contains(text(),'Add Base User-I [OCC]')]"
ADD_BASE_USER_BTN			="xpath=.//*[@id='ctl00_MainContent_RepeaterServiceCtrl_ctl02_btnAddtoCart']"
CONTINUE_BTN				="xpath=.//*[@id='MainContent_btnContinue']"
SITE_SERVICE_CONFIG			="xpath=.//*[@id='MainContent_NestedGrid_SiteServiceConfig']/div"
SELECT_SITE_BTN				="xpath=.//*[@id='MainContent_NestedGrid_lnkbtnAddSite']"
SITE_LIST					="xpath=.//*[@id='MainContent_UpdatePanel1']/div[1]"
COUNTRY_DROPDOWN			="xpath=.//*[@id='s2id_MainContent_RightMainPanel_ControlPanel_ctl00_ddlCountry']/a"
COUNTRY_INPUT				="xpath=.//*[@id='select2-drop']/div/input"
SITE_LOADING				="xpath=.//*[@id='PageOverlay']"
UPDATE_BTN					="xpath=.//*[@id='MainContent_NestedGrid_rptSite_childRptService_0_btnConfigure_0']"
CONFIG_PAGE					="xpath=.//*[@id='MainContent_UPServiceConfig']/div"
DEVICE_TYPE_DROPDOWN		="xpath=.//*[@id='s2id_MainContent_ATT_1_11034']/a"
FIRST_NAME_INPUT			="xpath=.//*[@id='MainContent_ATT_1_11029']"
LAST_NAME_INPUT				="xpath=.//*[@id='MainContent_ATT_1_11030']"
EMAIL_INPUT					="xpath=.//*[@id='MainContent_ATT_1_11961']"
PUBLIC_NUM_INPUT			="xpath=.//*[@id='MainContent_ATT_1_5577']"
PRIVATE_NUM_INPUT			="xpath=.//*[@id='MainContent_ATT_1_4499']"
OPTIONAL_MGS_DROPDOWN		="xpath=.//*[@id='s2id_MainContent_ATT_1_11035']/a"
USERSELF_ACCESS_DROPDOWN	="xpath=.//*[@id='s2id_MainContent_ATT_1_11032']/a"
CLASS_OF_SERVICE_INPUT		="xpath=.//*[@id='MainContent_ATT_1_2825']"
DESCRIPTIVE_TEXT_INPUT		="xpath=.//*[@id='MainContent_ATT_1_11033']"
REQUEST_FORM_PAGE			="xpath=.//*[@id='RequestFormPanel']"
CONFIRMATION_PAGE			="xpath=.//*[@id='ConfirmationPanel']/div[2]"
CUSTOMER_REFERENCE_INPUT	="xpath=.//*[@id='MainContent_txt_CustomerReference']"
SUBMIT_BTN					="xpath=.//*[@id='MainContent_btnSubmit']"
CONFIRMATION_PANEL			="xpath=//*[@id='ConfirmationPanel']/div[2]/table[2]/tbody/tr[1]/th[2]"


