#Products in the quote
BLOCKER												= "xpath=.//div[@class='blockUI blockMsg blockPage']"
CBOX_ADDITIONAL_PRODUCT								= "xpath=.//tr[2]//input[@id='checks1']"
DD_ADDITONAL_PRODUCT_ORDER_TYPE						= "xpath=.//tr[2]/td[3]/div[2]/select[@class='form-control ng-pristine ng-valid']"
BTN_ADD_PRODUCT_TO_QUOTE							= "xpath=.//button[contains(text(),'Add Product to Quote')]"
LINK_ADDITIONAL_PRODUCT_PROVIDE_CONFIGURATION		= "xpath=.//tr[3]//a[contains(text(),'Provide')]"
LINK_ADDITIONAL_PRODUCT_CEASE_CONFIGURATION			= "xpath=.//tr[3]//a[contains(text(),'Cease')]"
LOADING_MESSAGE										= "xpath=.//*[@id='loadingMessage']"
REMOVEMODIFY										= "xpath=.//input[@title='Remove/Modify selected product']"
CREATING_PRODUCT									= "xpath=.//div[@id='creating-product-spinner']"
LINK_BASE_CONFIGURATION								= "xpath=.//li[*]/div/div/span[@title='Base Configuration']"
LINK_ADMIN_SELF_SERVE								= "xpath=.//li[*]/div/div/span[@title='Admin Self Serve']"
LINK_LINE_SERVICE_OCC								= "xpath=.//li[*]/div/div/span[@title='Line Service-OCC']"
LINK_USER_SELF_SERVE								= "xpath=.//li[*]/div/div/span[@title='User Self Serve']"
ASSET_TO_DELETE										= "xpath= //input[@ng-checked='isSelectedAll()']"
STATUS_LOADING										= "xpath=.//*[@id='statusBarModal']"
PROCESSING_MESSAGE									= "xpath=.//*[text()='Processing...']"
LOADING_PRODUCTS									= "xpath=.//*[text()='Loading products']"
PERFORM_DELETING									= "xpath=.//*[text()='Performing Deleting']"
LINK_QUOTE_OPT_DETAILS								= "xpath=.//*[@id='quoteOption']"
CBOX_LIST_QUOTE_OPT_DETAILS							= "xpath=.//input[@name='listOfQuoteOptionItems']"
BTN_IMPORT_PRODUCT									= "xpath=.//a[@id='importProduct']"
BTN_IMPORT_PRODUCT_BROWSE							= "xpath=.//input[@id='eCRFSheet']"
RFO_INVALID											= "xpath= .//*[@id='orders']/tbody/tr/td[6][contains (text(),'RFO invalid')]"
BTN_OK_RFO											= "xpath=.//div[@role='dialog'][not(contains(@style,'display: none'))]//button"	
UPLOAD_SUCCESSFUL									= "xpath=.//*[text()='Upload Successful']"
STATUS_SUBMITTED									= "xpath=.//*[text()='Submitted']"
NEW_QUANTITY                                        = "xpath= //*[@id='table-row-index-0']/td[5]/div/div[3]/input"
MODIFY_CONFIGURATION                                = "xpath=.//html/body/div/div[1]/section/div/div/div/div/div/div[2]/table/tbody/tr[3]/td[3]/div[1]/a"
ADD_PRODUCT                                         = "xpath=.//*[@id='configurator-container']/div[5]/div[1]/div[1]/button[1]"
MODIFY_PRODUCT_LIST                                 = "//table[@id='siteTable']/tbody/tr"
RFO_IMPORT_ICON                                     = "xpath=.//*[@id='rfoImport']/img"
RFO_EXPORT_ICON                                     = "xpath=.//*[@id='rfoExport']/img"
QUOTE_CREATE_BTN									= "xpath=.//*[@id='createQuoteForm']/div/button[contains(text(),'Create')]"

#NEW R52
#Configure Product Screen
LINE_SERVICE_OCC									= "xpath=.//span[@title='Line Service-OCC']"
LINE_SERVICE_OCC_BASE_CONFIG						= "xpath=.//span[@title='Line Service-OCC']/..//span[@title='Base Configuration']"
LINE_SERVICE_ACTION_BOX								= "xpath=.//div[@rel='LINE SERVICE ACTION']/div[@id='']"
LINE_SERVICE_ACTION_DD								= "xpath=.//div[@rel='LINE SERVICE ACTION']/div/select"
TABLE_BASE_CONFIG									= "xpath=.//table[@class='bulkGUI']"
ISA_NO_CONCUR_SESSIONS								= "xpath=.//div[@rel='QUANTITY']/div[contains(@class,'text-content')]"
ISA_NO_CONCUR_SESSIONS_INPUT						= "xpath=.//div[@rel='QUANTITY']/div/input"
ISA_NO_REGISTRATION									= "xpath=.//div[@rel='REGISTRATIONS QUANTITY']/div[contains(@class,'text-content')]"
ISA_NO_REGISTRATION_INPUT							= "xpath=.//div[@rel='REGISTRATIONS QUANTITY']/div/input"

##R56-PRICING STAGE CHANGE FROM RFI TO BAFO##
BAFO_RADIOBUTTON			="xpath=.//*[@id='quote-stage-bafo']"
WARNING_WINDOW				="xpath=.//*[@id='quoteStageConfirmationDialog']"
BAFO_YES_BTN				="xpath=.//*[@id='quoteStageYesButton']"

#added by Azry 02072018 - AA
AUTOATTENDANT_EXTN									="xpath=.//span[contains(@title,'Auto-Attendant Extn')]"
CONFIGURE_LINK										="xpath=.//a[text()='Configure']"
LOADING_BEFORE_CONFIGURE							="xpath=.//div[@class='status-bar']"
CONFIGURE_AUTO_ATTENDANT_EXTENSION					="xpath=.//span[text()='Auto-Attandent Extension']/../..//*[@id='creatable_rel_ctnr']"
ADD_SELECTED_ITEM_BTN								="xpath=.//*[@title='Add selected items']"
CONFIGURE_BTN_OK									="xpath=.//div[@role='dialog'][not(contains(@style,'display: none'))]//button[contains(text(),'Ok')]"
LOADING_AFTER_CONFIGURE								="xpath=.//div[@class='status-bar']/p[contains(text(),'Number of outstanding saves')]"
AUTOATTENDANT_EXTN_BASE_CONFIG						="xpath=.//span[contains(@title,'Auto-Attendant Extn')]/..//span[@title='Base Configuration']"
AUTOATTENDANT_BASE_CONFIG_QUANTITY					="//div[@rel='QUANTITY']"
AUTOATTENDANT_BASE_CONFIG_QUANTITY_INPUT			="//div[@class='grid_Add_newVal control-content']/input"
#end added by Azry